CREATE TABLE IF NOT EXISTS GADGETS(
    GADGET_ID TEXT PRIMARY KEY,
    GADGET_NAME TEXT,
    PRICE REAL,
    CATEGORY_CODE TEXT
);

INSERT INTO GADGETS (GADGET_ID, GADGET_NAME, PRICE, CATEGORY_CODE)
VALUES
    ('G1', 'SMART WATCH', 199.99, 'WEAR-01'),
    ('G2', 'WIRELESS EARBUDS', 89.00, 'AUDIO-02'),
    ('G3', 'PORTABLE CHARGER', 45.50, 'ACC-03'),
    ('G4', 'BLUETOOTH SPEAKER', 120.00, 'AUDIO-02'),
    ('G5', 'TABLET STYLUS', 99.00, 'ACC-03'),
    ('G6', 'VR HEADSET', 399.00, 'ENT-04'),
    ('G7', 'E-READER', 129.99, 'ENT-04'),
    ('G8', 'SMART LIGHT BULB', 25.00, 'HOME-05'),
    ('G9', 'SECURITY CAMERA', 150.00, 'HOME-05'),
    ('G10', 'FITNESS TRACKER', 60.00, 'WEAR-01');

SELECT PRICE
    FROM GADJETS
    WHERE PRICE = (SELECT MAX(PRICE0) FROM GADJETS)
SELECT PRO_NAME, PRO_PRICE
    FROM PRODUCT
    WHERE PRICE = (SELECT MAX(PRICE) FROM GADJETS);