CREATE TABLE IF NOT EXISTS WARE (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    CATEGORY_ID TEXT,
    SUPPLIER_ID TEXT,
    PRICE REAL
);

INSERT INTO WARE (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, SUPPLIER_ID, PRICE) VALUES
    ('P-501', 'ULTRA MONITOR', 'DISP', 'SUP-10', 450.00),
    ('P-502', 'MECHANICAL KEY', 'PERI', 'SUP-12', 120.50),
    ('P-503', 'WIRELESS MOUSE', 'PERI', 'SUP-12', 55.00),
    ('P-604', 'STUDIO MIC', 'AUDIO', 'SUP-15', 299.00),
    ('P-605', 'NOISE CANCEL HP', 'AUDIO', 'SUP-15', 185.00),
    ('P-701', 'G-SYNC CABLE', 'ACC', 'SUP-10', 25.00),
    ('P-808', 'WEBCAM PRO', 'VIDEO', 'SUP-22', 95.00),
    ('P-910', 'DESK LAMP', 'OFFICE', 'SUP-05', 42.00);

SELECT PRODUCT_NAME
FROM WARE
GROUP BY PRODUCT_NAME;


SELECT SUPPLIER_ID
FROM WARE
ORDER BY SUPPLIER_ID;