CREATE TABLE IF NOT EXISTS DEPART (
    EMPLOYEE_ID TEXT,
    NAME TEXT,
    DEPARTMENT_ID TEXT,
    MANAGER_ID TEXT,
    SALARY REAL
);

INSERT INTO DEPART (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES
    ('100', 'STEVEN KING', '90', '100', 24000),
    ('102', 'NEENA KOCCHAR', '90', '100', 17000),
    ('102', 'LEX DEHAAR', '90', '102', 9000),
    ('103', 'BRUCE LEE', '68', '103', 4800),
    ('104', 'DIANA WILLS', '60', '103', 25000),
    ('105', 'VALLI PATOR', '50', '100', 4200),
    ('9730', 'LUV HAMI', '60', '102', 5000),
    ('106', 'DAVID AUSTIN', '90', '100', 6000);

SELECT DEPARTMENT_ID AS 'Department Code'
FROM DEPART
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, SUM(SALARY)
FROM DEPART
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS 'Department Code',
COUNT(*) AS 'No of Employees',
SUM(SALARY) AS 'Total Salary',
FROM DEPART
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS 'Department Code',
SUM(SALARY) AS 'Total Salary',
FROM DEPART
WHERE MANAGER_ID = '103'
GROUP BY DEPARTMENT_ID;