CREATE TABLE IF NOT EXISTS STUDENTSS (
   ROLL_NO TEXT PRIMARY KEY,
   NAME TEXT NOT NULL,
   ADDRESS TEXT,
   PHONE TEXT,
   AGE INTEGER
);

INSERT INTO STUDENTSS (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
    ('1', 'RAM', 'DELHI', '*****', 18),
    ('2', 'RAMESH', 'GURAGAON', '*****', 18),
    ('3', 'SUJIT', 'ROHTAK', '*****', 20),
    ('4', 'SURESH', 'DELHI', '*****', 18),
    ('5', 'AMAN', 'ROHTAK', '*****', 20),
    ('6', 'HARSH', 'GURAGAON', '*****', 18);


SELECT * FROM STUDENTSS;
SELECT * FROM STUDENTSS WHERE AGE = 18 AND ADDRESS = 'DELHI';
SELECT * FROM STUDENTSS WHERE AGE = 18 AND NAME = 'RAM';
SELECT * FROM STUDENTSS WHERE NAME = 'RAM' OR NAME = 'SUJIT';
SELECT * FROM STUDENTSS WHERE NAME = 'RAM' OR AGE = 20;
SELECT * FROM STUDENTSS WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');